name = "Scheduling"
uuid = "3046eef8-5348-48c9-b840-6c15f76662f3"
authors = ["Bartek Przybylski <bap@amu.edu.pl>", "Sascha Hunold <sascha@hunoldscience.net>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataStructures = "≥ 0.17.0"
GLPK = "≥ 0.12.0"
JLD2 = "≥ 0.1.12"
JuMP = "≥ 0.21.0"
Plots = "≥ 0.29.0"
PyPlot = "≥ 2.8.0"
julia = "≥ 1.0.0"
